import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, updateDoc, where, writeBatch } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { DEFAULT_EXERCISES } from "@/data/default-exercises";
import { normalizeSearchText } from "@/lib/utils";
import type { BodyWeight, Exercise, PhysicalAssessment, SeedResult, Workout, WorkoutSession } from "@/types";
const list = async <T>(path: string, clauses: Parameters<typeof query>[1][] = []) => (await getDocs(query(collection(db, path), ...clauses))).docs.map(d => ({ id: d.id, ...d.data() }) as T);
function validateDefaultExercises() { if (DEFAULT_EXERCISES.length !== 202) throw Error("O dataset padrão deve possuir exatamente 202 exercícios."); const ids=new Set<string>(), orders=new Set<number>(), names=new Set<string>(); for(const item of DEFAULT_EXERCISES){ if(!item.id||!item.name||!item.muscleGroup||!item.videoUrl.startsWith("https://")) throw Error(`Exercício inválido: ${item.name||item.id}`); if(ids.has(item.id)||orders.has(item.sortOrder)||names.has(normalizeSearchText(item.name))) throw Error(`Duplicidade encontrada: ${item.name}`); ids.add(item.id);orders.add(item.sortOrder);names.add(normalizeSearchText(item.name)); } for(let i=1;i<=202;i++){ if(!orders.has(i)) throw Error(`Ordem padrão ausente: ${i}`); } }
export const exercises = { list: () => list<Exercise>("exercises", [orderBy("name")]), save: async (data: Omit<Exercise,"id">, id?: string) => id ? updateDoc(doc(db,"exercises",id), { ...data, updatedAt: serverTimestamp() }) : addDoc(collection(db,"exercises"), { ...data, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }), remove: (id: string) => deleteDoc(doc(db,"exercises",id)), seedDefaultLibrary: async (): Promise<SeedResult> => { validateDefaultExercises(); const existing=await getDocs(collection(db,"exercises")); const existingById=new Set(existing.docs.map(item=>item.id)); const result:SeedResult={total:202,created:0,updated:0,skipped:0,errors:0}; for(let start=0;start<DEFAULT_EXERCISES.length;start+=400){ const batch=writeBatch(db); for(const item of DEFAULT_EXERCISES.slice(start,start+400)){ const known=existingById.has(item.id); batch.set(doc(db,"exercises",item.id),{...item,updatedAt:serverTimestamp(),...(known?{}:{createdAt:serverTimestamp()})},{merge:true}); known?result.updated++:result.created++; } await batch.commit(); } return result; } };
export const workouts = { list: (uid: string) => list<Workout>("workouts", [where("ownerId","==",uid), orderBy("createdAt","desc")]), save: async (data: Omit<Workout,"id">, id?: string) => id ? updateDoc(doc(db,"workouts",id), { ...data, updatedAt: serverTimestamp() }) : addDoc(collection(db,"workouts"), { ...data, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }), remove: (id:string) => deleteDoc(doc(db,"workouts",id)), duplicate: async (workout:Workout) => addDoc(collection(db,"workouts"), { ownerId:workout.ownerId, name:`${workout.name} - Cópia`, title:`${workout.title} - Cópia`, description:workout.description, muscleGroups:workout.muscleGroups, active:workout.active, exercises:workout.exercises, createdAt:serverTimestamp(), updatedAt:serverTimestamp() }) };
export const weights = { list: (uid: string) => list<BodyWeight>("bodyWeights", [where("ownerId","==",uid), orderBy("date","asc")]), save: (data: Omit<BodyWeight,"id">) => addDoc(collection(db,"bodyWeights"), { ...data, createdAt: serverTimestamp() }), update: (id:string,data:Pick<BodyWeight,"date"|"weight"|"note">) => updateDoc(doc(db,"bodyWeights",id),{...data,updatedAt:serverTimestamp()}), remove: (id:string) => deleteDoc(doc(db,"bodyWeights",id)) };
export const assessments = { list: (uid: string) => list<PhysicalAssessment>("physicalAssessments", [where("ownerId","==",uid), orderBy("date","desc")]), save: (data: Omit<PhysicalAssessment,"id">) => addDoc(collection(db,"physicalAssessments"), { ...data, createdAt: serverTimestamp() }) };
export const sessions = { list: (uid: string) => list<WorkoutSession>("workoutSessions", [where("ownerId","==",uid), orderBy("startedAt","desc"), limit(30)]), get: async (id:string) => { const d=await getDoc(doc(db,"workoutSessions",id)); return d.exists() ? ({id:d.id,...d.data()} as WorkoutSession):null; }, getActive: async(uid:string) => { const result=await getDocs(query(collection(db,"workoutSessions"),where("ownerId","==",uid),where("status","==","active"),limit(1))); return result.empty?null:({id:result.docs[0].id,...result.docs[0].data()} as WorkoutSession); }, start: async (uid:string, workout:Workout) => addDoc(collection(db,"workoutSessions"), { ownerId:uid, workoutId:workout.id, workoutName:workout.name, startedAt:serverTimestamp(), status:"active", totalVolume:0, totalSets:0, exercises:workout.exercises.map(e=>({id:e.id,exerciseId:e.exerciseId,name:e.name,order:e.order,target:e,sets:Array.from({length:e.sets},(_,i)=>({id:`${e.id}-${i}`,load:e.suggestedLoad??0,reps:e.repsMin,completed:false,volume:0}))})) }), save: (id:string, data:Partial<WorkoutSession>) => updateDoc(doc(db,"workoutSessions",id), data) };
