import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, updateDoc, where } from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { BodyWeight, Exercise, PhysicalAssessment, Workout, WorkoutSession } from "@/types";
const list = async <T>(path: string, clauses: Parameters<typeof query>[1][] = []) => (await getDocs(query(collection(db, path), ...clauses))).docs.map(d => ({ id: d.id, ...d.data() }) as T);
export const exercises = { list: () => list<Exercise>("exercises", [orderBy("name")]), save: async (data: Omit<Exercise,"id">, id?: string) => id ? updateDoc(doc(db,"exercises",id), { ...data, updatedAt: serverTimestamp() }) : addDoc(collection(db,"exercises"), { ...data, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }), remove: (id: string) => deleteDoc(doc(db,"exercises",id)) };
export const workouts = { list: (uid: string) => list<Workout>("workouts", [where("ownerId","==",uid), orderBy("createdAt","desc")]), save: async (data: Omit<Workout,"id">, id?: string) => id ? updateDoc(doc(db,"workouts",id), { ...data, updatedAt: serverTimestamp() }) : addDoc(collection(db,"workouts"), { ...data, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }) };
export const weights = { list: (uid: string) => list<BodyWeight>("bodyWeights", [where("ownerId","==",uid), orderBy("date","asc")]), save: (data: Omit<BodyWeight,"id">) => addDoc(collection(db,"bodyWeights"), { ...data, createdAt: serverTimestamp() }), remove: (id:string) => deleteDoc(doc(db,"bodyWeights",id)) };
export const assessments = { list: (uid: string) => list<PhysicalAssessment>("physicalAssessments", [where("ownerId","==",uid), orderBy("date","desc")]), save: (data: Omit<PhysicalAssessment,"id">) => addDoc(collection(db,"physicalAssessments"), { ...data, createdAt: serverTimestamp() }) };
export const sessions = { list: (uid: string) => list<WorkoutSession>("workoutSessions", [where("ownerId","==",uid), orderBy("startedAt","desc"), limit(30)]), get: async (id:string) => { const d=await getDoc(doc(db,"workoutSessions",id)); return d.exists() ? ({id:d.id,...d.data()} as WorkoutSession):null; }, start: async (uid:string, workout:Workout) => addDoc(collection(db,"workoutSessions"), { ownerId:uid, workoutId:workout.id, workoutName:workout.name, startedAt:serverTimestamp(), status:"active", totalVolume:0, totalSets:0, exercises:workout.exercises.map(e=>({id:e.id,exerciseId:e.exerciseId,name:e.name,order:e.order,target:e,sets:Array.from({length:e.sets},(_,i)=>({id:`${e.id}-${i}`,load:e.suggestedLoad??0,reps:e.repsMin,completed:false,volume:0}))})) }), save: (id:string, data:Partial<WorkoutSession>) => updateDoc(doc(db,"workoutSessions",id), data) };
