"use client";
import { Check, Plus } from "lucide-react";
import { Button, Card } from "@/components/ui";
import { trainingStageLabel } from "@/lib/training-methods";
import type { SessionExercise, TrainingSet } from "@/types";

export function TrainingMethodExecution({ exercise, exerciseIndex, onChange, onComplete, onAdd, onRemove, onSync }: { exercise: SessionExercise; exerciseIndex: number; onChange: (exerciseIndex: number, setIndex: number, data: Partial<TrainingSet>) => void; onComplete: (exerciseIndex: number, setIndex: number, completed: boolean) => void; onAdd: (exerciseIndex: number) => void; onRemove: (exerciseIndex: number, setIndex: number) => void; onSync: () => void }) {
  const method = exercise.target.methodSnapshot;
  return <Card className="exercise method-execution"><div className="method-execution-title"><div><h2>{exercise.name}</h2><span className="method-chip">{method?.name ?? "Séries normais"}{exercise.target.groupId ? ` · posição ${(exercise.target.groupPosition ?? 0) + 1}` : ""}</span></div>{method?.fullDescription && <details><summary>Como executar</summary><p>{method.fullDescription}</p></details>}</div><p>{exercise.target.repsMin}–{exercise.target.repsMax} repetições · descanso {exercise.target.restSeconds}s</p>{exercise.sets.map((trainingSet, setIndex) => <div className={`set method-stage ${trainingSet.completed ? "completed" : ""}`} key={trainingSet.id}><b>{trainingStageLabel(trainingSet)}</b><label className="set-field"><span>Carga</span><input aria-label={`Carga: ${trainingStageLabel(trainingSet)}`} type="number" min="0" step="0.1" value={trainingSet.load} onChange={(event) => onChange(exerciseIndex, setIndex, { load: Number(event.target.value) })} onBlur={onSync}/></label><span>kg ×</span>{trainingSet.durationSeconds !== undefined ? <label className="set-field"><span>Tempo</span><input aria-label={`Tempo: ${trainingStageLabel(trainingSet)}`} type="number" min="0" step="1" value={trainingSet.durationSeconds} onChange={(event) => onChange(exerciseIndex, setIndex, { durationSeconds: Number(event.target.value) })} onBlur={onSync}/><span>s</span></label> : <label className="set-field"><span>Reps</span><input aria-label={`Repetições: ${trainingStageLabel(trainingSet)}`} type="number" min="0" step="1" value={trainingSet.reps} onChange={(event) => onChange(exerciseIndex, setIndex, { reps: Number(event.target.value) })} onBlur={onSync}/></label>}{trainingSet.tempo && <small>{trainingSet.tempo.eccentric}-{trainingSet.tempo.pause}-{trainingSet.tempo.concentric}-{trainingSet.tempo.top}</small>}{trainingSet.toFailure && <small>até a falha</small>}{trainingSet.completed ? <button className="text-button" onClick={() => onComplete(exerciseIndex, setIndex, false)}>Desfazer <Check className="success" size={16}/></button> : <Button onClick={() => onComplete(exerciseIndex, setIndex, true)}>CONCLUIR</Button>}{setIndex >= exercise.target.sets && <button className="text-button" disabled={trainingSet.completed} onClick={() => onRemove(exerciseIndex, setIndex)}>Remover</button>}</div>)}<button className="text-button" onClick={() => onAdd(exerciseIndex)}><Plus size={16}/> Adicionar série normal</button></Card>;
}

