"use client";
import { AppShell } from "@/components/app-shell";
import { Guard } from "@/components/guard";
import { Button, Card, Empty, Loading } from "@/components/ui";
import { exerciseMuscleGroups, normalizeSearchText } from "@/lib/utils";
import { exercises } from "@/services/data";
import type { Exercise, SeedResult } from "@/types";
import { ExternalLink, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

function Admin(){const[list,setList]=useState<Exercise[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[group,setGroup]=useState(""),[order,setOrder]=useState<"default"|"az"|"za">("default"),[importing,setImporting]=useState(false),[result,setResult]=useState<SeedResult|null>(null);
const reload=async()=>{setLoading(true);try{setList(await exercises.list())}finally{setLoading(false)}};useEffect(()=>{reload()},[]);
const filtered=useMemo(()=>{const query=normalizeSearchText(search);return list.filter(item=>!group||item.muscleGroup===group).filter(item=>!query||[item.name,item.nameEn,...(item.aliases??[])].filter(Boolean).some(value=>normalizeSearchText(value!).includes(query))).sort((a,b)=>order==="default"?(a.sortOrder??9999)-(b.sortOrder??9999):order==="az"?a.name.localeCompare(b.name,"pt-BR"):b.name.localeCompare(a.name,"pt-BR"));},[list,search,group,order]);
async function seed(){if(!confirm("Deseja importar/atualizar a biblioteca padrão de exercícios? Os exercícios existentes serão atualizados quando necessário e não serão duplicados."))return;setImporting(true);setResult(null);try{setResult(await exercises.seedDefaultLibrary());await reload()}catch(error){alert(error instanceof Error?error.message:"A importação falhou.")}finally{setImporting(false)}}
return <AppShell><header><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Biblioteca de exercícios</h1><p>Gerencie a biblioteca global usada na montagem dos treinos.</p></header><Card><div className="library-head"><div><h2>Biblioteca padrão</h2><p>{list.length} exercícios cadastrados</p></div><Button onClick={seed} disabled={importing}>{importing?"IMPORTANDO EXERCÍCIOS...":"IMPORTAR BIBLIOTECA PADRÃO"}</Button></div>{result&&<p className="success">Biblioteca atualizada: {result.total} processados · {result.created} criados · {result.updated} atualizados · {result.skipped} ignorados · {result.errors} erros.</p>}</Card><Card><div className="library-filters"><label><span className="sr-only">Pesquisar exercícios</span><span className="search-input"><Search size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Pesquisar nome, inglês ou alias"/></span></label><label>Grupo<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">Todos os grupos</option>{exerciseMuscleGroups.map(item=><option key={item}>{item}</option>)}</select></label><label>Ordenar<select value={order} onChange={event=>setOrder(event.target.value as "default"|"az"|"za")}><option value="default">Ordem padrão</option><option value="az">A-Z</option><option value="za">Z-A</option></select></label>{(search||group||order!=="default")&&<button className="text-button" onClick={()=>{setSearch("");setGroup("");setOrder("default")}}>Limpar filtros</button>}</div><p className="muted">{filtered.length} exercícios encontrados</p>{loading?<Loading/>:filtered.length?<div className="exercise-library">{filtered.map(item=><article className="library-item" key={item.id}><div><strong>{item.name}</strong>{item.nameEn&&<small>{item.nameEn}</small>}<span>{item.muscleGroup}</span></div>{item.videoUrl&&<a className="video-link" href={item.videoUrl} target="_blank" rel="noopener noreferrer" aria-label={`Ver execução de ${item.name}`}><ExternalLink size={16}/> Ver execução</a>}</article>)}</div>:<Empty title="Nenhum exercício encontrado." detail="Tente pesquisar outro nome ou remover os filtros."/>}</Card></AppShell>}
export default function Page(){return <Guard admin><Admin/></Guard>}
