"use client";

import { AppShell } from "@/components/app-shell";
import { Guard } from "@/components/guard";
import { useAuth } from "@/components/providers";
import { Button, Card, Empty, Loading } from "@/components/ui";
import { exerciseMuscleGroups, normalizeSearchText } from "@/lib/utils";
import { exercises, sessions, workouts } from "@/services/data";
import type { Exercise, TrainingSet, Workout, WorkoutExercise, WorkoutSession } from "@/types";
import { Check, ExternalLink, Plus, Search, Timer } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const newExercise = (exercise: Exercise, order: number): WorkoutExercise => ({ id: crypto.randomUUID(), exerciseId: exercise.id, name: exercise.name, order, sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90 });
const reorder = (items: WorkoutExercise[]) => items.map((item, index) => ({ ...item, order: index + 1 }));
const calculateTotals = (items: WorkoutSession["exercises"]) => items.reduce((totals, exercise) => exercise.sets.reduce((next, item) => item.completed ? { totalSets: next.totalSets + 1, totalVolume: next.totalVolume + item.load * item.reps } : next, totals), { totalSets: 0, totalVolume: 0 });

function Work() {
  const { user, profile } = useAuth();
  const uid = user?.uid;
  const [plans, setPlans] = useState<Workout[]>([]);
  const [library, setLibrary] = useState<Exercise[]>([]);
  const [builder, setBuilder] = useState<Workout | null | undefined>(undefined);
  const [draft, setDraft] = useState<WorkoutExercise[]>([]);
  const [name, setName] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState("");
  const [search, setSearch] = useState(""); const [group, setGroup] = useState("");
  const [importing, setImporting] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [session, setSession] = useState<WorkoutSession | null>(null); const [active, setActive] = useState<WorkoutSession | null>(null); const [rest, setRest] = useState(0);

  const reload = async () => { if (uid) { setPlans(await workouts.list(uid)); setActive(await sessions.getActive(uid)); } };
  useEffect(() => { if (!uid) return; workouts.list(uid).then(setPlans); sessions.getActive(uid).then(setActive); exercises.list().then(setLibrary); }, [uid]);
  useEffect(() => { if (!rest) return; const timer = window.setInterval(() => setRest(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [rest]);
  const filteredLibrary = useMemo(() => library.filter(item => item.active && (!group || item.muscleGroup === group)).filter(item => { const query = normalizeSearchText(search); return !query || [item.name, item.nameEn, ...(item.aliases ?? [])].filter(Boolean).some(value => normalizeSearchText(value!).includes(query)); }), [library, search, group]);
  if (!uid) return <Loading />;
  function openBuilder(workout?: Workout) { setBuilder(workout ?? null); setDraft(workout ? reorder(workout.exercises) : []); setName(workout?.name ?? ""); setTitle(workout?.title ?? ""); setDescription(workout?.description ?? ""); setSearch(""); setGroup(""); setSaving(false); setMessage(""); }
  function updateDraft(id: string, data: Partial<WorkoutExercise>) { setDraft(items => items.map(item => item.id === id ? { ...item, ...data } : item)); }
  function addExercise(exercise: Exercise) { if (draft.some(item => item.exerciseId === exercise.id)) { setMessage("Este exercício já foi adicionado ao treino."); return; } setDraft(items => [...items, newExercise(exercise, items.length + 1)]); setMessage(""); }
  function moveExercise(index: number, direction: -1 | 1) { setDraft(items => { const next = [...items]; const destination = index + direction; if (destination < 0 || destination >= next.length) return items; [next[index], next[destination]] = [next[destination], next[index]]; return reorder(next); }); }
  async function saveWorkout(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || !title.trim() || !draft.length) { setMessage("Informe nome, título e adicione ao menos um exercício antes de criar o treino."); return; } if (draft.some(item => item.sets < 1 || item.repsMin < 1 || item.repsMax < item.repsMin || item.restSeconds < 0)) { setMessage("Revise séries, repetições e descanso dos exercícios adicionados."); return; } const editing=Boolean(builder); setSaving(true); setMessage(""); try { const data = { ownerId: uid!, name: name.trim(), title: title.trim(), description: description.trim() || undefined, muscleGroups: [...new Set(draft.map(item => library.find(exercise => exercise.id === item.exerciseId)?.muscleGroup).filter((item): item is string => Boolean(item)))], active: builder?.active ?? true, exercises: reorder(draft) }; await workouts.save(data, builder?.id); await reload(); setBuilder(undefined); setMessage(editing ? "Treino atualizado com sucesso." : "Treino criado com sucesso."); } catch (error) { const code=typeof error==="object"&&error!==null&&"code" in error?String(error.code):""; setMessage(code.includes("permission-denied") ? "Não foi possível criar o treino porque sua sessão não tem permissão. Entre novamente e tente de novo." : code.includes("unavailable")||code.includes("network") ? "Sem conexão com o servidor. Verifique sua internet e tente novamente." : "Não foi possível criar o treino. Revise os dados e tente novamente."); } finally { setSaving(false); } }
  async function importLibrary() { setImporting(true); try { await exercises.seedDefaultLibrary(); setLibrary(await exercises.list()); } catch { setMessage("Não foi possível importar a biblioteca. Entre como administrador e tente novamente."); } finally { setImporting(false); } }
  async function start(workout: Workout) { const existing = await sessions.getActive(uid!); if (existing) { setActive(existing); setMessage("Você possui um treino em andamento."); return; } const reference = await sessions.start(uid!, workout); const created = await sessions.get(reference.id); setSession(created); setActive(created); }
  async function persist(next: WorkoutSession) { const totals = calculateTotals(next.exercises); const saved = { ...next, ...totals }; setSession(saved); setActive(saved); await sessions.save(saved.id, { exercises: saved.exercises, ...totals }); }
  async function updateSet(exerciseIndex: number, setIndex: number, data: Partial<TrainingSet>) { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise, currentExercise) => currentExercise !== exerciseIndex ? exercise : { ...exercise, sets: exercise.sets.map((item, currentSet) => currentSet !== setIndex ? item : { ...item, ...data, volume: (data.completed ?? item.completed) ? (data.load ?? item.load) * (data.reps ?? item.reps) : 0 }) }) }; await persist(next); }
  async function addSet(exerciseIndex: number) { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise, index) => index !== exerciseIndex ? exercise : { ...exercise, sets: [...exercise.sets, { id: crypto.randomUUID(), load: exercise.target.suggestedLoad ?? 0, reps: exercise.target.repsMin, completed: false, volume: 0 }] }) }; await persist(next); }
  async function removeSet(exerciseIndex: number, setIndex: number) { if (!session) return; const target = session.exercises[exerciseIndex].sets[setIndex]; if (target.completed || !confirm("Remover esta série extra?")) return; const next = { ...session, exercises: session.exercises.map((exercise, index) => index !== exerciseIndex ? exercise : { ...exercise, sets: exercise.sets.filter((_, itemIndex) => itemIndex !== setIndex) }) }; await persist(next); }
  async function finish() { if (!session || !confirm("Finalizar treino?")) return; const start = session.startedAt?.seconds ? session.startedAt.seconds * 1000 : Date.now(); await sessions.save(session.id, { status: "completed", endedAt: new Date() as never, durationSeconds: Math.max(0, Math.round((Date.now() - start) / 1000)) }); setSession(null); setActive(null); }
  async function cancel() { if (!session || !confirm("Cancelar este treino em andamento?")) return; await sessions.save(session.id, { status: "cancelled", endedAt: new Date() as never }); setSession(null); setActive(null); }

  if (session) return <AppShell><header><p className="eyebrow">EM ANDAMENTO</p><h1>{session.workoutName}</h1><p>{session.totalSets} séries concluídas · {Math.round(session.totalVolume).toLocaleString("pt-BR")} kg</p></header>{rest > 0 && <Card className="rest"><Timer /><strong>{String(Math.floor(rest / 60)).padStart(2, "0")}:{String(rest % 60).padStart(2, "0")}</strong><Button onClick={() => setRest(0)}>PULAR DESCANSO</Button><button className="text-button" onClick={() => setRest(value => value + 15)}>+15s</button></Card>}{session.exercises.map((exercise, exerciseIndex) => <Card key={exercise.id} className="exercise"><h2>{exercise.name}</h2><p>{exercise.target.repsMin}–{exercise.target.repsMax} repetições · descanso {exercise.target.restSeconds}s</p>{exercise.sets.map((trainingSet, setIndex) => <div className="set" key={trainingSet.id}><b>{setIndex + 1}</b><input aria-label="Carga" type="number" min="0" value={trainingSet.load} onChange={event => void updateSet(exerciseIndex, setIndex, { load: Number(event.target.value) })} /><span>kg ×</span><input aria-label="Repetições" type="number" min="0" value={trainingSet.reps} onChange={event => void updateSet(exerciseIndex, setIndex, { reps: Number(event.target.value) })} />{trainingSet.completed ? <button className="text-button" onClick={() => void updateSet(exerciseIndex, setIndex, { completed: false })}>Desfazer <Check className="success" size={16} /></button> : <Button onClick={() => { void updateSet(exerciseIndex, setIndex, { completed: true }); setRest(exercise.target.restSeconds); }}>CONCLUIR</Button>}{setIndex >= exercise.target.sets && <button className="text-button" onClick={() => void removeSet(exerciseIndex, setIndex)}>Remover</button>}</div>)}<button className="text-button" onClick={() => void addSet(exerciseIndex)}><Plus size={16} /> Adicionar série</button></Card>)}<Button className="finish" onClick={() => void finish()}>FINALIZAR TREINO</Button><button className="text-button" onClick={() => void cancel()}>Cancelar treino</button></AppShell>;

  return <AppShell><header><p className="eyebrow">SESSÃO</p><h1>Qual treino vamos fazer?</h1><Button onClick={() => openBuilder() }><Plus size={16} /> NOVO TREINO</Button></header>{message && <p className={message.includes("sucesso") ? "success" : "error"}>{message}</p>}
    {active && <Card><span>TREINO EM ANDAMENTO</span><h2>{active.workoutName}</h2><p>Há uma sessão ativa salva. Retome-a para continuar de onde parou.</p><Button onClick={() => setSession(active)}>RETOMAR TREINO</Button><button className="text-button" onClick={async () => { if (confirm("Descartar a sessão em andamento?")) { await sessions.save(active.id, { status: "cancelled", endedAt: new Date() as never }); setActive(null); } }}>Descartar sessão</button></Card>}
    {builder !== undefined && <Card className="workout-builder-card">
      <div className="builder-title"><div><span>{builder ? "EDIÇÃO" : "NOVO TREINO"}</span><h2>{builder ? "Editar treino" : "Monte seu treino"}</h2><p>Adicione os exercícios à lista e crie o treino somente quando terminar.</p></div><button type="button" className="text-button" onClick={() => setBuilder(undefined)}>Fechar</button></div>
      {!library.length ? <div className="empty"><strong>Biblioteca ainda não foi importada.</strong><span>{profile?.role === "admin" ? "Importe os exercícios padrão para liberar o criador." : "Peça para o administrador importar a biblioteca padrão."}</span>{profile?.role === "admin" && <Button onClick={() => void importLibrary()} disabled={importing}>{importing ? "IMPORTANDO..." : "IMPORTAR 202 EXERCÍCIOS"}</Button>}</div> : <form className="workout-builder" onSubmit={saveWorkout}>
        <div className="form-grid workout-info"><label>Nome do treino<input required value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: Treino A" /></label><label>Título<input required value={title} onChange={event => setTitle(event.target.value)} placeholder="Ex.: Peito e tríceps" /></label><label className="workout-description">Descrição<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Opcional" /></label></div>
        <section className="builder-section"><div className="builder-section-title"><div><span>1</span><div><h3>Adicionar exercício</h3><p>Pesquise na biblioteca e use o botão para colocar cada exercício na lista.</p></div></div></div><div className="library-filters"><label><span className="sr-only">Pesquisar exercícios</span><span className="search-input"><Search size={17}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Nome, inglês ou alias"/></span></label><label>Grupo<select value={group} onChange={event => setGroup(event.target.value)}><option value="">Todos os grupos</option>{exerciseMuscleGroups.map(item => <option key={item}>{item}</option>)}</select></label></div><div className="exercise-picker">{filteredLibrary.map(item => { const added=draft.some(candidate=>candidate.exerciseId===item.id); return <article key={item.id} className={`library-item ${added ? "selected" : ""}`}><div><strong>{item.name}</strong><small>{item.muscleGroup}</small></div><div>{item.videoUrl && <a className="video-link" href={item.videoUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/> Vídeo</a>}<button type="button" className={`exercise-add-button ${added ? "added" : ""}`} onClick={() => addExercise(item)} disabled={added}>{added ? <><Check size={16}/> ADICIONADO</> : <><Plus size={16}/> ADICIONAR EXERCÍCIO</>}</button></div></article>})}</div>{!filteredLibrary.length && <Empty title="Nenhum exercício encontrado." detail="Tente outro nome ou remova os filtros."/>}</section>
        <section className="builder-section"><div className="builder-section-title"><div><span>2</span><div><h3>Exercícios adicionados <b>{draft.length}</b></h3><p>Ajuste séries, repetições, descanso e a ordem antes de criar.</p></div></div></div>{!draft.length && <Empty title="Nenhum exercício adicionado" detail="Use “Adicionar exercício” na biblioteca acima para montar a lista."/>}{draft.map((item, index) => <div className="card workout-draft-item" key={item.id}><div className="row"><strong>{index + 1}. {item.name}</strong><span><button type="button" className="draft-order-button" onClick={() => moveExercise(index, -1)} disabled={index === 0} aria-label={`Mover ${item.name} para cima`}>↑</button><button type="button" className="draft-order-button" onClick={() => moveExercise(index, 1)} disabled={index === draft.length - 1} aria-label={`Mover ${item.name} para baixo`}>↓</button><button type="button" className="draft-remove-button" onClick={() => setDraft(items => reorder(items.filter(candidate => candidate.id !== item.id)))}>Remover</button></span></div><div className="form-grid"><label>Séries<input type="number" min="1" value={item.sets} onChange={event => updateDraft(item.id, { sets: Number(event.target.value) })} /></label><label>Descanso (s)<input type="number" min="0" value={item.restSeconds} onChange={event => updateDraft(item.id, { restSeconds: Number(event.target.value) })} /></label><label>Repetições mín.<input type="number" min="1" value={item.repsMin} onChange={event => updateDraft(item.id, { repsMin: Number(event.target.value) })} /></label><label>Repetições máx.<input type="number" min="1" value={item.repsMax} onChange={event => updateDraft(item.id, { repsMax: Number(event.target.value) })} /></label><label>Carga sugerida (kg)<input type="number" min="0" value={item.suggestedLoad ?? ""} onChange={event => updateDraft(item.id, { suggestedLoad: event.target.value === "" ? undefined : Number(event.target.value) })} /></label><label>Observação<textarea value={item.notes ?? ""} onChange={event => updateDraft(item.id, { notes: event.target.value || undefined })} /></label></div></div>)}</section>
        <div className="workout-form-actions"><Button type="submit" className="workout-submit" disabled={saving}>{saving ? "SALVANDO..." : builder ? "SALVAR ALTERAÇÕES" : `CRIAR TREINO (${draft.length} ${draft.length === 1 ? "EXERCÍCIO" : "EXERCÍCIOS"})`}</Button><button type="button" className="text-button" onClick={() => setBuilder(undefined)} disabled={saving}>Cancelar</button></div>
      </form>}
    </Card>}
    <div className="cards">{plans.filter(item => item.active).map(workout => <Card key={workout.id}><h2>{workout.title}</h2><p>{workout.description}</p><small>{workout.exercises.length} exercícios</small><div><Button onClick={() => void start(workout)} disabled={Boolean(active)}>INICIAR</Button><button className="text-button" onClick={() => openBuilder(workout)}>Editar</button><button className="text-button" onClick={async () => { await workouts.duplicate(workout); await reload(); }}>Duplicar</button><button className="text-button" onClick={async () => { if (confirm(`Excluir o treino ${workout.name}? As sessões já realizadas serão preservadas.`)) { await workouts.remove(workout.id); await reload(); } }}>Excluir</button><button className="text-button" onClick={async () => { await workouts.save({ ...workout, active: false }, workout.id); await reload(); }}>Arquivar</button></div></Card>)}</div>{!plans.filter(item => item.active).length && builder === undefined && <Empty title="Nenhum treino ativo" detail="Use “Novo treino” para montar o seu." />}
  </AppShell>;
}

export default function Training() { return <Guard><Work /></Guard>; }
